### ISSUE TITLE
The evaluation instruction is not found in the guideline...

### ISSUE THREAD

**Issue by zhimin-z** [BAAI-DCAI/Multimodal-Robustness-Benchmark#4]
<img width="859" alt="image" src="https://github.com/user-attachments/assets/137b35a5-b1aa-403d-91a6-d2e9a93e5ecd">
The evaluation instruction is not found in the guideline...
<img width="867" alt="image" src="https://github.com/user-attachments/assets/5010713f-58bb-42b6-a004-bc231fbb461d">

**Comment by chrisx599** [comment]
Sorry, our previous url linked to the dev version. It's accessible now.
